# changes here will be overwritten by copier
_commit: 35098c8
_src_path: /Users/pcastellazzi/Workspace/code/python-project/
github_repo: https://github.com/pcastellazzi/license-scanner.git
github_user: pcastellazzi
project_module: license_scanner
python_version: '3.11'
user_email: pablo.castellazzi@icloud.com
user_name: Pablo Castellazzi
