version = 1

[[annotations]]
SPDX-FileCopyrightText = "Copyright © 2025 Pablo Castellazzi <pablo.castellazzi@icloud.com>"
SPDX-License-Identifier = "MIT"
precedence = "override"

path = [
    ".copier-answers.yml",
    ".coveragerc",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".python-version",
    "GNUmakefile",
    "README.md",
    "pyproject.toml",
    "ruff.toml",
    "scripts/**",
    "src/**",
    "tests/**",
    "uv.lock",
]
