builtins = ["_"]
target-version = "py311"

[format]
docstring-code-format = true
docstring-code-line-length = 78

[lint]
fixable = ["ALL"]
ignore = ["COM", "D"]
select = ["ALL"]

[lint.per-file-ignores]
"scripts/**/*.py" = [
    "T201", # allow print in scripts
]
"tests/**/*.py" = [
    "PLR2004", # magic numbers in tests are ok
    "S101",    # assert in tests is ok
]

[lint.flake8-tidy-imports]
ban-relative-imports = "all"

[lint.isort]
known-first-party = ["license_scanner"]
